-- PR-01 · Frozen Baseline Patch 1, P-5 §4.1: tenant root.
-- Frozen shape: md.company (company_id uuid PK, rnc text NOT NULL UNIQUE, legal_name text NOT NULL).
-- company_id values are UUIDv7 generated by the application (ADR-029); no database default on purpose.
CREATE SCHEMA md;

CREATE TABLE md.company (
  company_id  uuid NOT NULL,
  rnc         text NOT NULL,
  legal_name  text NOT NULL,
  CONSTRAINT company_pk PRIMARY KEY (company_id),
  CONSTRAINT company_rnc_uq UNIQUE (rnc)
);
