-- UX3-01 · Critical flows per area, server side (approved errata E-UX3-1…14): the reconciliations and their findings in words.

-- E-UX3-2: each reconciliation's Spanish name and what to do about its findings, shown by the close and reconciliation screens.
ALTER TABLE rec.recon_definition ADD COLUMN name text, ADD COLUMN guidance text;
UPDATE rec.recon_definition d SET name = v.name, guidance = v.guidance FROM (VALUES
  ('AP-GL', 'Cuentas por pagar contra contabilidad',
   'Compara, por proveedor, el saldo abierto de sus facturas en cuentas por pagar con su saldo en la cuenta de control de proveedores (AP_CONTROL). Revise con «Explicar este asiento» los movimientos del proveedor en la cuenta de control hasta encontrar el que no corresponde a una factura o un pago, y corríjalo. Bloquea el cierre de cuentas por pagar (AP-REC).'),
  ('INV-VALUE-GL', 'Valor del inventario contra contabilidad',
   'Compara, por área de valoración e ítem, el valor del inventario con el saldo de las cuentas de inventario (materia prima, producto terminado y en tránsito). Una diferencia indica un movimiento de inventario sin su asiento o un asiento sin movimiento: las excepciones de VALUE-GL-LINK y ACC-EVIDENCE suelen señalar el documento. Bloquea el cierre de inventario (INV-MOV).'),
  ('INV-QTY-BALANCE', 'Existencias contra movimientos',
   'Comprueba que las existencias de cada ubicación, ítem y lote sean la suma de sus movimientos, y que la cantidad valorizada de cada área sea la suma de las existencias de sus plantas. Es una verificación interna: una diferencia no se corrige con un ajuste; repórtela a soporte técnico con la clave de la excepción. Bloquea INV-MOV.'),
  ('INV-VALUE-BALANCE', 'Valoración contra entradas de valor',
   'Comprueba que el valor de cada área e ítem sea la suma de sus entradas de valor. Es una verificación interna: una diferencia indica un error técnico; repórtela a soporte con la clave de la excepción. Bloquea INV-MOV.'),
  ('VAL-RESIDUAL', 'Valor residual del inventario',
   'Busca ítems sin existencias que conservan valor (valor huérfano, error) y ítems con existencias cuyo valor es cero o negativo (aviso). El valor huérfano se elimina con el ajuste de valor residual (R-06), que aprueba el Controller; el valor no positivo se revisa con el costo de las últimas recepciones y facturas del ítem. El valor huérfano bloquea INV-MOV.'),
  ('ACC-EVIDENCE', 'Evidencia contable de los documentos',
   'Comprueba que cada documento contabilizado (recepciones y sus reversas y correcciones, facturas de proveedor y de venta, notas de crédito, cobros, depósitos, retenciones, pagos y cargos bancarios) tenga su asiento vivo, que uno revertido tenga su reversa y que uno no contabilizado no tenga asiento. Una excepción señala una alteración o un fallo técnico: no se corrige desde la aplicación; repórtela a soporte y a auditoría con la clave del documento. Bloquea el cierre del componente del documento.'),
  ('VALUE-GL-LINK', 'Enlace entre valor de inventario y contabilidad',
   'Comprueba que cada entrada de valor de inventario tenga exactamente una línea contable por el mismo importe y que ninguna línea de las cuentas de inventario carezca de entrada de valor. Es una verificación interna del motor de contabilización: repórtela a soporte con la clave. Bloquea INV-MOV.'),
  ('GRNI-AGING', 'Recibido no facturado antiguo',
   'Avisa de las líneas de órdenes de compra recibidas y aún no facturadas cuya primera recepción tiene más días que los de la política de inventario (grni_aging_alert_days). Pida la factura al proveedor y regístrela en Cuentas por pagar, o corrija o revierta la recepción si no correspondía. Es un aviso: no bloquea cierres.'),
  ('BANK-GL', 'Banco contra contabilidad',
   'Para cada cuenta bancaria, al corte, el saldo contable debe ser el saldo del extracto más las partidas en tránsito identificadas (pagos, cobros, depósitos y cargos que el banco aún no muestra, y líneas del extracto aún no contabilizadas). Importe el extracto que cubra la fecha de corte, concilie sus líneas con los pagos y cobros, reconozca los cargos bancarios y aclare las partidas antiguas. Bloquea el cierre de bancos (BANK-REC).'),
  ('PAY-APPL', 'Aplicación de pagos',
   'Comprueba que cada pago liberado aplique exactamente su monto a facturas, que lo pagado de cada factura (original menos abierto) sea la suma de sus aplicaciones y que cada aplicación tenga su línea contable R-09. Es una verificación interna: repórtela a soporte con la clave. Bloquea BANK-REC y AP-REC.'),
  ('MANUAL-EVIDENCE', 'Evidencia de los ajustes manuales',
   'Comprueba que cada ajuste manual contabilizado tenga su asiento con los mismos totales (y su reversa si fue revertido o es de reversa automática) y que no exista ningún asiento manual sin un ajuste que lo respalde. Una excepción indica una alteración: repórtela a auditoría y a soporte. Bloquea el cierre de provisiones (ACR-NTX y ACR-TAX).'),
  ('TB-BALANCED', 'Balanza de comprobación cuadrada',
   'Comprueba que cada asiento tenga débitos iguales a créditos. Un asiento descuadrado solo es posible por una alteración de la base de datos: repórtelo de inmediato a soporte y a auditoría. Bloquea ACR-NTX y ACR-TAX.'),
  ('STRUCT-COVERAGE', 'Cobertura de los estados financieros',
   'Avisa de cuentas activas sin clase, de la falta de una estructura vigente del balance general o del estado de resultados y de cuentas que no están en ninguna línea de la estructura vigente; sin eso los estados financieros no cuadran. Asigne la clase en el catálogo de cuentas y agregue la cuenta a una línea en Configuración › Estructuras. Es un aviso: no bloquea cierres.'),
  ('MIGRATION-CLEARING', 'Cuenta puente de migración',
   'Avisa mientras la cuenta puente de migración (MIGRATION_CLEARING) no esté en cero. Termine de cargar los saldos de apertura o corrija el lote que dejó la diferencia. Es un aviso: no bloquea cierres.'),
  ('AR-GL', 'Cuentas por cobrar contra contabilidad',
   'Compara, por cliente, el saldo abierto de sus documentos en cuentas por cobrar con su saldo en la cuenta de control de clientes (AR_CONTROL). Revise con «Explicar este asiento» los movimientos del cliente en la cuenta de control hasta encontrar el que no corresponde a una factura, nota de crédito o cobro. Bloquea el cierre de cuentas por cobrar (AR-REC).'),
  ('CONTRACT-ASSET', 'Entregado no facturado',
   'Por cada línea de conduce entregada, lo entregado menos lo facturado, al precio del pedido, debe ser su saldo de activo de contrato o de cuenta por cobrar no facturada. También avisa de lo entregado sin facturar por más días que los de la política (unbilled_aging_alert_days): facture esas entregas. La diferencia bloquea AR-REC; el aviso no.'),
  ('RECEIPT-APPL', 'Aplicación de cobros',
   'Comprueba que cada cobro registrado reparta su monto entre aplicaciones y saldo sin aplicar, que lo cobrado de cada factura sea la suma de aplicaciones, retenciones y notas de crédito confirmadas (o su anulación), que cada aplicación tenga su línea contable y que los saldos de cobros sin aplicar y de efectivo en tránsito coincidan con los cobros. Es una verificación interna: repórtela a soporte con la clave. Bloquea AR-REC y BANK-REC.'),
  ('FISC-DOC', 'Comprobantes fiscales pendientes',
   'Lista las facturas y notas de crédito emitidas hasta la fecha de corte cuyo e-CF aún no tiene respuesta final. Registre en cada documento la respuesta del proveedor de facturación electrónica antes de cerrar. Bloquea AR-REC.'),
  ('DELIVERY-OPEN', 'Conduces en tránsito',
   'Avisa de los conduces que salieron de la planta hace más horas que las de la política (delivery_open_alert_hours) y aún no tienen prueba de entrega. Registre la entrega (POD), la devolución o la pérdida. Es un aviso: no bloquea cierres.'),
  ('WIP-GL', 'Producción en proceso contra contabilidad',
   'Por cada acumulador de costos, el saldo de producción en proceso (WIP) debe ser el consumo de los resúmenes de turno contabilizados menos su estándar de materiales y menos las variaciones ya liquidadas. Una diferencia es un error interno: repórtela a soporte con la clave. Bloquea el cierre de la liquidación de costos (COST-SET).'),
  ('WIP-OPEN', 'Acumuladores sin liquidar',
   'Lista los acumuladores de costos de meses ya terminados que siguen abiertos. Liquide la producción del mes en Producción para llevar las variaciones al resultado. Bloquea COST-SET.'),
  ('SHIFT-OPEN', 'Corridas sin contabilizar',
   'Lista las corridas de producción hasta la fecha de corte que siguen en proceso. Registre y contabilice su resumen de turno, o anule la corrida si no se produjo. Bloquea el cierre del día de operación (OP-DAY) y COST-SET.'),
  ('USAGE-TOLERANCE', 'Consumo fuera de tolerancia',
   'Avisa cuando el consumo real de un material en un turno se aparta del teórico de la receta más que la tolerancia de la política de producción (usage_tolerance_pct). Revise el pesaje y el consumo registrado con el supervisor, o la receta si la diferencia se repite. Es un aviso: no bloquea cierres.'),
  ('CURING-OVERDUE', 'Curado vencido',
   'Avisa de los lotes que siguen en curado después de las horas máximas de su receta. Libere el lote si está listo, o bloquéelo o descártelo si no cumple. Es un aviso: no bloquea cierres.'),
  ('PRODUCTION-CLOSE-ORDER', 'Orden de cierre de producción',
   'En un período con producción, el día de operación (OP-DAY) se cierra antes que la liquidación de costos (COST-SET), y esta antes que el inventario (INV-MOV). Cierre primero el componente que indica la excepción. Bloquea COST-SET e INV-MOV.'),
  ('AUTH-CONSUMPTION', 'Consumo de autorizaciones fiscales',
   'Comprueba que lo consumido de cada línea de autorización fiscal sea la suma de sus consumos menos sus liberaciones, y que cada línea de factura e-CF 44 consuma su neto menos lo acreditado por notas de crédito. Es una verificación interna: repórtela a soporte con la clave. Bloquea AR-REC.'),
  ('EXEMPT-WITHOUT-AUTH', 'Factura exenta sin autorización',
   'Lista las facturas emitidas sin ITBIS que no son e-CF 44 aunque tienen ítems que la regla de ITBIS de ventas grava. Emita una nota de crédito y vuelva a facturar con el ITBIS que corresponde, o como e-CF 44 si el cliente tiene una autorización vigente. Bloquea AR-REC.'),
  ('AUTH-EXPIRY', 'Autorizaciones fiscales por vencer',
   'Avisa de las autorizaciones fiscales en uso que vencen dentro de los días de la política (authorization_expiry_alert_days) o cuyo plazo de proyecto terminó. Pida al cliente la renovación, o deje de facturarle como exento. Es un aviso: no bloquea cierres.'),
  ('TAX-606', 'Formato 606 contra contabilidad',
   'Para el mes de la fecha de corte, el ITBIS por adelantar del 606 debe coincidir con el ITBIS de compras (ITBIS_RECOVERABLE) contabilizado en el mes; también avisa de compras sin clasificación de bienes y servicios y de retenciones de ISR sin tipo. Complete la regla de clasificación 606 o el tipo de retención en Reglas fiscales y revise las facturas contabilizadas en un mes distinto al de su comprobante. Es un aviso: no bloquea cierres.'),
  ('CONTROLS-WAIVED', 'Controles dispensados',
   'Lista los comandos del mes de la fecha de corte en que un superadministrador dispensó un control de cuatro ojos. Revise cada uno con el Controller y deje constancia del motivo. Es un aviso para auditoría: no bloquea cierres.')
) AS v (code, name, guidance) WHERE d.recon_code = v.code;
ALTER TABLE rec.recon_definition ALTER COLUMN name SET NOT NULL, ALTER COLUMN guidance SET NOT NULL;

-- E-UX3-2: every classification a reconciliation produces (Reconciliations.cs, BankGl.cs and the warnings of tax.report_606), in
-- words. ReconciliationTextTests requires a row for each one found in those sources.
CREATE TABLE rec.recon_classification (
  classification text NOT NULL,
  name           text NOT NULL,
  guidance       text NOT NULL,
  CONSTRAINT recon_classification_pk PRIMARY KEY (classification)
);
INSERT INTO rec.recon_classification (classification, name, guidance) VALUES
  ('AP_GL_DIFFERENCE', 'Diferencia entre cuentas por pagar y su cuenta de control',
   'El saldo abierto de las facturas del proveedor no coincide con su saldo en AP_CONTROL. Revise sus asientos en la cuenta de control con «Explicar este asiento» y corrija el que no corresponda a una factura o un pago.'),
  ('VALUE_GL_DIFFERENCE', 'Diferencia entre el valor del inventario y la contabilidad',
   'El valor del ítem en el área no coincide con el saldo de las cuentas de inventario. Busque en VALUE-GL-LINK y ACC-EVIDENCE el documento sin asiento o el asiento sin movimiento.'),
  ('STOCK_LEDGER_DIFFERENCE', 'Existencias distintas de sus movimientos',
   'Las existencias de la ubicación, ítem y lote no son la suma de sus movimientos. Error interno: repórtelo a soporte con la clave.'),
  ('VALUATION_QUANTITY_DIFFERENCE', 'Cantidad valorizada distinta de las existencias',
   'La cantidad valorizada del área no es la suma de las existencias de sus plantas. Error interno: repórtelo a soporte con la clave.'),
  ('VALUATION_LEDGER_DIFFERENCE', 'Valor distinto de sus entradas de valor',
   'El valor del ítem en el área no es la suma de sus entradas de valor. Error interno: repórtelo a soporte con la clave.'),
  ('ORPHAN_VALUE', 'Valor sin existencias',
   'El ítem no tiene existencias en el área pero conserva valor. El Controller debe aprobar el ajuste de valor residual (R-06) de esa área e ítem.'),
  ('NON_POSITIVE_VALUE', 'Existencias con valor cero o negativo',
   'Hay existencias pero su valor es cero o negativo. Revise el costo de las últimas recepciones, correcciones y facturas del ítem.'),
  ('POSTED_WITHOUT_JOURNAL', 'Documento contabilizado sin asiento',
   'El documento figura como contabilizado pero no tiene asiento vivo. Posible alteración: no lo corrija desde la aplicación; repórtelo a soporte y a auditoría.'),
  ('REVERSED_WITHOUT_JOURNAL', 'Documento revertido sin asientos',
   'El documento está revertido pero no tiene ni su asiento ni su reversa. Repórtelo a soporte y a auditoría.'),
  ('REVERSED_WITH_LIVE_JOURNAL', 'Documento revertido con asiento vivo',
   'El documento o pago está revertido pero su asiento sigue sin reversa. Repórtelo a soporte y a auditoría.'),
  ('NOT_POSTED_WITH_JOURNAL', 'Documento no contabilizado con asiento',
   'El documento no está contabilizado pero tiene un asiento vivo. Repórtelo a soporte y a auditoría.'),
  ('RELEASED_WITHOUT_JOURNAL', 'Pago liberado sin asiento',
   'El pago está liberado o compensado pero no tiene su asiento R-09 vivo. Repórtelo a soporte y a auditoría.'),
  ('CHARGE_WITHOUT_JOURNAL', 'Cargo bancario sin asiento',
   'La línea del extracto se reconoció como cargo bancario pero no tiene su asiento. Repórtelo a soporte.'),
  ('MANUAL_JOURNAL_EVIDENCE', 'Ajuste manual sin evidencia completa',
   'Los totales del ajuste no coinciden con su asiento, o falta la reversa de un ajuste revertido o de reversa automática. Repórtelo a auditoría y a soporte.'),
  ('RULELESS_JOURNAL_WITHOUT_ADJUSTMENT', 'Asiento manual sin ajuste',
   'Existe un asiento de ajuste manual que no corresponde a ningún ajuste. Posible alteración: repórtelo a auditoría y a soporte.'),
  ('JOURNAL_UNBALANCED', 'Asiento descuadrado',
   'El asiento tiene débitos distintos de sus créditos. Solo es posible por una alteración de la base de datos: repórtelo de inmediato a soporte y a auditoría.'),
  ('MIGRATION_CLEARING_NOT_ZERO', 'Cuenta puente de migración con saldo',
   'Faltan saldos de apertura por cargar o un lote dejó diferencia. Complete la migración hasta que el saldo quede en cero.'),
  ('ACCOUNT_WITHOUT_CLASS', 'Cuenta sin clase',
   'Asigne a la cuenta su clase (activo, pasivo, patrimonio, ingreso, costo o gasto) en el catálogo de cuentas.'),
  ('STRUCTURE_MISSING', 'Falta la estructura del estado financiero',
   'No hay una estructura vigente del balance general o del estado de resultados. Créela y actívela en Configuración › Estructuras.'),
  ('ACCOUNT_NOT_IN_STRUCTURE', 'Cuenta fuera de la estructura',
   'La cuenta no está en ninguna línea de la estructura vigente de su estado financiero. Agréguela a una línea en Configuración › Estructuras.'),
  ('BALANCE_SHEET_DIFFERENCE', 'El balance no cuadra',
   'Una cuenta sin clase tiene saldo, por eso activo menos pasivo, patrimonio y resultado no da cero. Asigne la clase a las cuentas señaladas como «Cuenta sin clase».'),
  ('PAYMENT_APPLICATION_DIFFERENCE', 'Pago aplicado por un monto distinto',
   'Las aplicaciones vivas del pago no suman su monto, o un pago revertido conserva aplicaciones. Error interno: repórtelo a soporte con la clave.'),
  ('AP_DOCUMENT_APPLICATION_DIFFERENCE', 'Saldo de la factura distinto de sus pagos',
   'Lo pagado de la factura (original menos abierto) no es la suma de sus aplicaciones. Error interno: repórtelo a soporte con la clave.'),
  ('APPLICATION_WITHOUT_R09_LINE', 'Aplicación de pago sin su línea contable',
   'La aplicación no tiene exactamente una línea R-09 de cuentas por pagar por su importe. Error interno: repórtelo a soporte con la clave.'),
  ('VALUE_WITHOUT_GL', 'Entrada de valor sin asiento',
   'La entrada de valor de inventario no tiene línea contable. Error interno: repórtelo a soporte con la clave.'),
  ('VALUE_WITH_SEVERAL_GL', 'Entrada de valor con varias líneas contables',
   'La entrada de valor de inventario tiene más de una línea contable. Error interno: repórtelo a soporte con la clave.'),
  ('VALUE_GL_AMOUNT', 'Importe distinto entre la entrada de valor y su asiento',
   'La línea contable de la entrada de valor no tiene su mismo importe. Error interno: repórtelo a soporte con la clave.'),
  ('INVENTORY_GL_WITHOUT_VALUE', 'Línea de inventario sin entrada de valor',
   'Una línea de una cuenta de inventario no está enlazada a ninguna entrada de valor. Error interno: repórtelo a soporte con la clave.'),
  ('AR_GL_DIFFERENCE', 'Diferencia entre cuentas por cobrar y su cuenta de control',
   'El saldo abierto de los documentos del cliente no coincide con su saldo en AR_CONTROL. Revise sus asientos en la cuenta de control con «Explicar este asiento» y corrija el que no corresponda a un documento.'),
  ('CONTRACT_ASSET_DIFFERENCE', 'Entregado no facturado distinto de la contabilidad',
   'Lo entregado sin facturar de la línea, al precio del pedido, no coincide con su saldo de activo de contrato. Error interno: repórtelo a soporte con la clave.'),
  ('UNBILLED_AGED', 'Entregado sin facturar antiguo',
   'La línea lleva más días entregada sin facturar que los de la política. Facture la entrega desde Ventas › Facturación.'),
  ('RECEIPT_APPLICATION_DIFFERENCE', 'Cobro aplicado por un monto distinto',
   'Las aplicaciones más el saldo sin aplicar no suman el monto del cobro, o un cobro devuelto o revertido conserva aplicaciones. Error interno: repórtelo a soporte con la clave.'),
  ('AR_DOCUMENT_SETTLEMENT_DIFFERENCE', 'Saldo de la factura de venta distinto de lo cobrado',
   'Lo cobrado de la factura no es la suma de sus aplicaciones, retenciones y notas de crédito confirmadas. Error interno: repórtelo a soporte con la clave.'),
  ('APPLICATION_WITHOUT_P25_LINE', 'Aplicación de cobro sin su línea contable',
   'La aplicación no tiene exactamente una línea de cuentas por cobrar por su importe. Error interno: repórtelo a soporte con la clave.'),
  ('RECEIPT_GL_DIFFERENCE', 'Cobro distinto en la contabilidad',
   'El saldo del cobro en cobros sin aplicar o en efectivo en tránsito no coincide con el cobro. Error interno: repórtelo a soporte con la clave.'),
  ('FISCAL_DOCUMENT_PENDING', 'e-CF sin respuesta final',
   'Registre en la factura o nota de crédito la respuesta del proveedor de facturación electrónica.'),
  ('DELIVERY_OPEN', 'Conduce sin prueba de entrega',
   'Registre la prueba de entrega (POD), la devolución o la pérdida del conduce.'),
  ('WIP_GL_DIFFERENCE', 'Producción en proceso distinta de la contabilidad',
   'El saldo WIP del acumulador no es el consumo menos el estándar menos las variaciones liquidadas. Error interno: repórtelo a soporte con la clave.'),
  ('COLLECTOR_NOT_SETTLED', 'Acumulador de costos sin liquidar',
   'Liquide en Producción el acumulador de costos del mes terminado.'),
  ('RUN_NOT_POSTED', 'Corrida en proceso',
   'Contabilice el resumen de turno de la corrida, o anúlela si no se produjo.'),
  ('USAGE_OUT_OF_TOLERANCE', 'Consumo fuera de tolerancia',
   'Revise con el supervisor el pesaje y el consumo registrado; si la diferencia se repite, revise la receta.'),
  ('CURING_OVERDUE', 'Lote con curado vencido',
   'Libere el lote si está listo, o bloquéelo o descártelo si no cumple.'),
  ('CLOSE_ORDER', 'Componente cerrado fuera de orden',
   'Cierre primero el componente indicado en la clave: el día de operación (OP-DAY) antes que la liquidación de costos (COST-SET), y esta antes que el inventario (INV-MOV).'),
  ('AUTH_LINE_CONSUMPTION_DIFFERENCE', 'Consumo de la autorización distinto de sus movimientos',
   'Lo consumido de la línea de autorización no es la suma de sus consumos menos sus liberaciones. Error interno: repórtelo a soporte con la clave.'),
  ('INVOICE_CONSUMPTION_DIFFERENCE', 'Consumo de la línea de factura distinto de su neto',
   'La línea de la factura e-CF 44 no consume su neto menos lo acreditado por notas de crédito. Error interno: repórtelo a soporte con la clave.'),
  ('EXEMPT_WITHOUT_AUTHORIZATION', 'Factura exenta sin autorización',
   'Emita una nota de crédito y vuelva a facturar con ITBIS, o como e-CF 44 con la autorización vigente del cliente.'),
  ('PROJECT_TERM_ENDED', 'Plazo del proyecto terminado',
   'El plazo del proyecto de la autorización terminó: no facture más como exento con ella y pida al cliente la prórroga.'),
  ('AUTHORIZATION_EXPIRING', 'Autorización por vencer',
   'Pida al cliente la renovación de la autorización antes de su vencimiento.'),
  ('TAX606_ITBIS_DIFFERENCE', 'ITBIS del 606 distinto del contabilizado',
   'El ITBIS por adelantar del 606 del mes no coincide con ITBIS_RECOVERABLE contabilizado en el mes. Revise las facturas contabilizadas en un mes distinto al de su comprobante y los ajustes manuales a esa cuenta.'),
  ('CONTROL_WAIVED', 'Control de cuatro ojos dispensado',
   'Revise el comando con el Controller y deje constancia de por qué se dispensó el control.'),
  ('GRNI_AGED', 'Recibido sin factura',
   'Pida la factura al proveedor y regístrela, o corrija o revierta la recepción si no correspondía.'),
  ('CLASSIFICATION_MISSING', 'Compra sin clasificación 606',
   'Agregue la categoría del ítem a la regla de clasificación 606 vigente en Reglas fiscales.'),
  ('ISR_WITHHOLDING_TYPE_MISSING', 'Retención de ISR sin tipo',
   'Indique el tipo de retención de ISR en la regla de retención de compras, en Reglas fiscales.'),
  ('OPENING_DIFFERENCE', 'Saldo inicial del extracto distinto',
   'El saldo inicial del primer extracto importado no coincide con el saldo contable del banco antes de esa fecha. Revise el extracto importado y los movimientos anteriores de la cuenta.'),
  ('STATEMENT_MISSING', 'Falta el extracto bancario',
   'Importe el extracto de la cuenta que cubra la fecha de corte.'),
  ('BANK_GL_DIFFERENCE', 'El banco no cuadra con la contabilidad',
   'El saldo contable no es el saldo del extracto más las partidas en tránsito. Concilie las líneas del extracto, reconozca los cargos bancarios y revise los asientos manuales a la cuenta del banco.'),
  ('IN_TRANSIT_AGED', 'Partida en tránsito antigua',
   'La partida lleva más de 30 días sin aparecer en el banco, o la línea del extracto sin contabilizarse. Aclárela con el banco y concíliela o corríjala.');
CREATE TRIGGER recon_classification_immutable BEFORE UPDATE OR DELETE ON rec.recon_classification FOR EACH ROW EXECUTE FUNCTION core.reject_mutation();
GRANT SELECT ON rec.recon_classification TO rochell_app;
