using System.Text.Json.Nodes;
using Microsoft.AspNetCore.OpenApi;
using Microsoft.OpenApi;
using Rochell.Api.Auth;
using Rochell.Api.Endpoints;
using Rochell.Api.Http;
using Rochell.Platform.Commands;

namespace Rochell.Api.Hosting;

/// <summary>
/// E-PR18-7: the OpenAPI document the committed <c>openapi.json</c> is compared with and the web types are generated from.
/// It states the transport conventions: decimals are strings (ADR-015), command bodies omit the fields the server fills,
/// every command needs <c>Idempotency-Key</c> and the anti-CSRF header, and the session travels in a cookie.
/// </summary>
public static class OpenApiSetup
{
    public const string DocumentName = "v1";
    private const string CookieSecurityScheme = "sessionCookie";

    public static void AddRochellOpenApi(this IServiceCollection services)
        => services.AddOpenApi(DocumentName, options =>
        {
            options.AddDocumentTransformer((document, _, _) =>
            {
                document.Info = new OpenApiInfo
                {
                    Title = "Rochell Core API",
                    Version = DocumentName,
                    Description = "Vertical Slice #1 (Frozen Baseline v2.1.1). Decimal values are JSON strings (ADR-015).",
                };
                document.Servers = [];
                document.Components ??= new OpenApiComponents();
                document.Components.SecuritySchemes ??= new Dictionary<string, IOpenApiSecurityScheme>();
                document.Components.SecuritySchemes[CookieSecurityScheme] = new OpenApiSecurityScheme
                {
                    Type = SecuritySchemeType.ApiKey,
                    In = ParameterLocation.Cookie,
                    Name = SessionCookie.Name,
                    Description = "Session cookie set by the sign-in callback (E-PR18-2).",
                };
                return Task.CompletedTask;
            });

            options.AddOperationTransformer((operation, context, _) =>
            {
                var metadata = context.Description.ActionDescriptor.EndpointMetadata;
                var path = context.Description.RelativePath ?? string.Empty;
                if (path.StartsWith("api/v1/companies/", StringComparison.Ordinal) || path == "api/v1/session")
                {
                    operation.Security = [new OpenApiSecurityRequirement { [new OpenApiSecuritySchemeReference(CookieSecurityScheme, context.Document)] = [] }];
                }

                if (metadata.OfType<CommandEndpointMetadata>().Any() || string.Equals(context.Description.HttpMethod, "POST", StringComparison.OrdinalIgnoreCase))
                {
                    operation.Parameters ??= [];
                    if (metadata.OfType<CommandEndpointMetadata>().Any())
                    {
                        operation.Parameters.Add(new OpenApiParameter
                        {
                            Name = CommandRunner.IdempotencyKeyHeader,
                            In = ParameterLocation.Header,
                            Required = true,
                            Description = "Generated by the client once per intent (e.g. when the form opens); a retry with the same key returns the first result.",
                            Schema = new OpenApiSchema { Type = JsonSchemaType.String, MinLength = 1, MaxLength = 200 },
                        });
                    }

                    operation.Parameters.Add(new OpenApiParameter
                    {
                        Name = CsrfHeader.Name,
                        In = ParameterLocation.Header,
                        Required = true,
                        Description = "Anti-CSRF header; must be \"1\".",
                        Schema = new OpenApiSchema { Type = JsonSchemaType.String, Enum = [JsonValue.Create(CsrfHeader.Value)] },
                    });
                }

                return Task.CompletedTask;
            });

            options.AddSchemaTransformer((schema, context, _) =>
            {
                var type = context.JsonTypeInfo.Type;
                if (type == typeof(decimal) || type == typeof(decimal?))
                {
                    schema.Type = type == typeof(decimal) ? JsonSchemaType.String : JsonSchemaType.String | JsonSchemaType.Null;
                    schema.Format = "decimal";
                    schema.Pattern = "^-?[0-9]+(\\.[0-9]+)?$";
                }
                else if (type == typeof(DateTime) || type == typeof(DateTime?))
                {
                    // UtcDateTimeConverter: ISO 8601 with an offset, written as UTC.
                    schema.Type = type == typeof(DateTime) ? JsonSchemaType.String : JsonSchemaType.String | JsonSchemaType.Null;
                    schema.Format = "date-time";
                }
                else if (context.JsonPropertyInfo is null && typeof(ICommand).IsAssignableFrom(type) && schema.Properties is not null)
                {
                    foreach (var field in CommandRunner.ServerFields)
                    {
                        schema.Properties.Remove(field);
                        schema.Required?.Remove(field);
                    }
                }

                return Task.CompletedTask;
            });
        });
}
