// E-PR18b-11: errors are shown by code, in Spanish. Unknown codes fall back to the API message and the correlation id.
import { ApiError } from "@/api/client";

export const ERROR_MESSAGES: Readonly<Record<string, string>> = {
  SESSION_INVALID: "Su sesión no es válida. Inicie sesión de nuevo.",
  SESSION_EXPIRED: "Su sesión expiró. Inicie sesión de nuevo.",
  NOT_AUTHORIZED: "No tiene permiso para esta acción en esta empresa o planta.",
  STEP_UP_REQUIRED: "Esta acción requiere que vuelva a autenticarse.",
  CSRF_HEADER_REQUIRED: "Solicitud rechazada por seguridad. Recargue la página.",
  VERSION_CONFLICT: "El documento cambió mientras lo editaba. Recargue y vuelva a intentarlo.",
  CONCURRENCY_CONFLICT: "Hubo un conflicto con otra operación simultánea. Vuelva a intentarlo.",
  INVALID_REQUEST: "Los datos enviados no son válidos.",
  INVALID_PARAMETER: "Un filtro o parámetro no es válido.",
  NOT_FOUND: "El documento no existe o no pertenece a su planta.",
  SERVICE_UNAVAILABLE: "El servicio no está disponible en este ambiente.",
  INTERNAL_ERROR: "Error inesperado del sistema.",
  APPROVER_IS_CREATOR: "No puede aprobar un documento que usted creó.",
  APPROVAL_LIMIT_EXCEEDED: "El monto supera su límite de aprobación.",
  INVALID_STATE: "El documento no está en un estado que permita esta acción.",
  PLANT_MISMATCH: "El documento pertenece a otra planta.",
  SUPPLIER_NOT_ACTIVE: "El proveedor no está activo.",
  ITEM_NOT_ACTIVE: "El artículo no está activo.",
  UOM_NOT_CONVERTIBLE: "La unidad de medida no tiene conversión vigente para el artículo.",
  LINES_REQUIRED: "Agregue al menos una línea.",
  QUANTITY_INVALID: "La cantidad no es válida.",
  PRICE_INVALID: "El precio no es válido.",
  REASON_REQUIRED: "Indique el motivo.",
  RECEIPT_TOLERANCE_EXCEEDED: "La cantidad supera la tolerancia de recepción de la orden.",
  PURCHASE_ORDER_NOT_RECEIVABLE: "La orden no está aprobada para recibir.",
  LOCATION_NOT_IN_PLANT: "La ubicación no pertenece a la planta de la orden.",
  DUPLICATE_LINE: "Hay líneas repetidas.",
  WEIGH_TICKET_USED: "Ese ticket de báscula ya fue usado.",
  OCCURRED_IN_FUTURE: "La fecha y hora de la recepción no puede estar en el futuro.",
  GOODS_RECEIPT_NOT_REVERSIBLE: "La recepción no se puede reversar (sus lotes ya se movieron o está facturada).",
  ALREADY_INVOICED: "La cantidad ya fue facturada.",
  USE_RECEIPT_CORRECTION: "Use una corrección de recepción en lugar de una reversa.",
  QTY_EXCEPTION_NOT_APPROVABLE: "Un exceso de cantidad no se puede aprobar como excepción.",
  FISCAL_GATE_CLOSED: "No hay reglas fiscales activas para la fecha; no se puede contabilizar.",
  POSTING_PREREQUISITE_MISSING: "Falta configuración contable (regla de posteo, mapeo de cuentas o política) para contabilizar.",
  PERIOD_NOT_ENDED: "El período todavía no ha terminado.",
  COMPONENT_NOT_OPEN: "El componente no está abierto.",
  COMPONENT_NOT_CLOSED: "El componente no está cerrado.",
  INTEGRITY_NOT_SEALED: "Hay registros del período sin sellar; espere al sellador y vuelva a intentarlo.",
  RECONCILIATION_ERRORS: "Hay conciliaciones con errores que bloquean el cierre.",
  REOPEN_ALREADY_REQUESTED: "Ya hay una solicitud de reapertura pendiente.",
  REOPEN_NOT_REQUESTED: "No hay una solicitud de reapertura pendiente.",
  SAME_PERSON: "La misma persona no puede solicitar y aprobar.",
  FISCAL_NUMBER_INVALID: "El NCF no tiene un formato válido (B + 10 dígitos o E + 12 dígitos).",
  FISCAL_NUMBER_USED: "Ese NCF ya está registrado para el proveedor.",
  QTY_EXCEEDS_AVAILABLE: "La cantidad supera lo recibido y aún no facturado.",
  PO_LINE_NOT_INVOICEABLE: "La línea de la orden no se puede facturar.",
  AP_NOT_OPEN: "La cuenta por pagar ya tiene pagos o aplicaciones; no se puede reversar.",
  ALREADY_REVERSED: "El documento ya fue reversado.",
  EVIDENCE_REQUIRED: "Indique la evidencia (ticket corregido, foto o registro).",
  FOUR_EYES_REQUIRED: "Otra persona debe aprobar esta acción.",
  // FIN-1
  ACCOUNT_DUPLICATE: "Ya existe una cuenta con ese código.",
  ACCOUNT_INVALID: "La cuenta no es válida: revise código, nombre y clase.",
  ACCOUNT_HAS_BALANCE: "La cuenta tiene saldo; no se puede desactivar.",
  ACCOUNT_NOT_ALLOWED: "Los ajustes van solo a cuentas activas que no son de control; bancos, CxP e inventario se mueven por sus documentos.",
  LINES_INVALID: "Revise las líneas: cada una con débito o crédito mayor que cero (2 decimales) y al menos dos líneas.",
  JOURNAL_UNBALANCED: "Los débitos y los créditos deben ser iguales.",
  SUPPORT_INVALID: "El ajuste necesita su soporte: referencia y archivo.",
  STRUCTURE_INVALID: "La estructura no es válida: códigos únicos, una línea por cuenta y cuentas de las clases del reporte.",
  STRUCTURE_INCOMPLETE: "Hay cuentas activas sin línea en la estructura.",
  STRUCTURE_MISSING: "No hay una estructura de reporte aprobada.",
  ACCOUNT_CLASS_MISSING: "Hay cuentas activas sin clase.",
  DATE_INVALID: "La fecha no es válida.",
  LINE_NOT_FOUND: "La línea no existe en el documento.",
  RECEIPT_CORRECTION_NOT_PENDING: "La corrección ya no está pendiente.",
  RNC_INVALID: "El RNC no es válido.",
  RNC_DUPLICATE: "Ya existe un proveedor con ese RNC.",
  // VS#2: treasury.
  BANK_ACCOUNT_INVALID: "El banco o el número de cuenta no son válidos (número: 5 a 30 dígitos).",
  BANK_ACCOUNT_DUPLICATE: "Esa cuenta bancaria ya está registrada.",
  BANK_ACCOUNT_NOT_ACTIVE: "La cuenta bancaria está cerrada.",
  BANK_ACCOUNT_HAS_OPEN_ITEMS: "La cuenta tiene pagos pendientes o líneas del extracto sin conciliar.",
  GL_ACCOUNT_NOT_FOUND: "La cuenta contable no existe.",
  GL_ACCOUNT_NOT_ELIGIBLE: "La cuenta contable debe ser de control y no estar usada por otra cuenta bancaria ni por un mapa.",
  PARTY_BANK_ACCOUNT_NOT_VERIFIED: "La cuenta del proveedor no está verificada.",
  PARTY_BANK_ACCOUNT_NOT_PAYABLE: "La cuenta del proveedor todavía no se puede pagar (retención de 72 horas o reemplazada).",
  PAYMENT_NOT_PREPARED: "El pago ya no está preparado.",
  PAYMENT_NOT_REVERSIBLE: "Solo se revierte un pago liberado o compensado.",
  APPLICATIONS_REQUIRED: "Elija al menos una factura.",
  APPLICATION_DUPLICATE: "Una factura aparece dos veces en el pago.",
  APPLICATION_WRONG_SUPPLIER: "Todas las facturas deben ser del mismo proveedor.",
  APPLICATION_EXCEEDS_OPEN_AMOUNT: "El monto aplicado supera el saldo abierto de la factura.",
  AMOUNT_INVALID: "El monto no es válido (mayor que cero, máximo 2 decimales).",
  VALUE_DATE_BEFORE_INVOICE: "La fecha valor no puede ser anterior a la factura más reciente.",
  VALUE_DATE_IN_FUTURE: "Un pago se libera en su fecha valor o después.",
  BANK_FORMAT_MISSING: "No hay un formato de extracto para ese banco.",
  BANK_FILE_INVALID: "El archivo tiene filas que no se pueden leer; no se importó nada.",
  BANK_FILE_TOO_LARGE: "El archivo supera 5 MB.",
  STATEMENT_ALREADY_IMPORTED: "Ese archivo ya fue importado.",
  STATEMENT_FIELDS_REQUIRED: "El formato del banco no trae período o saldos: indíquelos.",
  STATEMENT_FIELDS_DISAGREE: "El período o los saldos indicados no coinciden con el archivo.",
  STATEMENT_BALANCE_MISMATCH: "Saldo inicial + créditos − débitos no da el saldo final.",
  LINE_OUTSIDE_PERIOD: "Hay líneas fuera del período del extracto; no se importó nada.",
  PERIOD_CLOSED: "El mes de esa fecha está cerrado (Bancos para un extracto, Ajustes contables para un ajuste); reábralo primero o use otra fecha.",
  LINE_NOT_UNMATCHED: "La línea ya no está sin conciliar.",
  LINE_NOT_MATCHED: "La línea no está conciliada.",
  LINE_NOT_DEBIT: "Esa acción es solo para líneas de débito.",
  PAYMENT_NOT_RELEASED: "Solo se concilia un débito con un pago liberado.",
  PAYMENT_NOT_REVERSED: "Una línea de crédito solo se concilia como devolución de un pago revertido.",
  PAYMENT_REVERSED: "La línea de un pago revertido queda conciliada.",
  RETURN_WITHOUT_TRANSFER: "El pago revertido nunca fue debitado por el banco: no hay devolución.",
  RETURN_ALREADY_MATCHED: "La devolución de ese pago ya está conciliada.",
  MATCH_WRONG_BANK_ACCOUNT: "La línea y el pago son de cuentas bancarias distintas.",
  MATCH_AMOUNT_DIFFERS: "El monto de la línea y el del pago no son iguales.",
  MATCH_DATE_OUTSIDE_WINDOW: "La fecha de la línea está fuera de la ventana permitida.",
  ROLE_UNKNOWN: "El rol no existe.",
  USER_INVALID: "El usuario no existe o no está activo.",
  SELF_REQUEST: "Nadie puede solicitar un rol para sí mismo.",
  ASSIGNMENT_NOT_FOUND: "El usuario ya no tiene ese rol.",
  ALREADY_ASSIGNED: "El usuario ya tiene ese rol.",
  REQUEST_NOT_FOUND: "La solicitud no existe.",
  REQUEST_NOT_PENDING: "La solicitud ya fue decidida.",
  SECOND_APPROVER_REQUIRED: "La decide una persona distinta de quien la pidió y del usuario afectado.",
  SOD_CONFLICT: "Ese rol choca con otro rol del usuario (segregación de funciones).",
  POLICY_MISSING: "Falta la política con los tramos de antigüedad: TREASURY para CxP, CREDIT para CxC (Contabilidad › Políticas).",
  // VS#3: customers, prices, fleet, opening stock, orders and deliveries.
  CUSTOMER_EXISTS: "Ya existe un cliente con ese RNC o cédula.",
  CUSTOMER_NOT_ACTIVE: "El cliente no está activo.",
  CUSTOMER_TERMS_REQUIRED: "El cliente necesita términos de crédito aprobados.",
  NOT_CUSTOMER: "Ese tercero no es cliente.",
  NOT_DRAFT: "Solo se puede cambiar mientras está en borrador.",
  FIELD_REQUIRED: "Complete los campos obligatorios.",
  FIELD_INVALID: "Un campo no tiene un formato válido.",
  NOT_FINISHED_GOOD: "El artículo no es un producto terminado.",
  IN_TRANSIT_EXISTS: "Hay unidades del producto en tránsito; apruebe el costo estándar cuando se entreguen o regresen.",
  RECIPE_NOT_ACTIVE: "La receta no está activa.",
  MATERIAL_PRICES_MISMATCH: "Debe dar un precio estándar para cada material de la receta, y solo para ellos.",
  PLATE_INVALID: "La placa no tiene un formato válido.",
  PLATE_DUPLICATE: "Ya existe un vehículo con esa placa.",
  NATIONAL_ID_INVALID: "La cédula debe tener 11 dígitos.",
  NATIONAL_ID_DUPLICATE: "Ya existe un chofer con esa cédula.",
  OPENING_FILE_INVALID: "El archivo de apertura tiene errores; revise el detalle.",
  OPENING_FILE_ALREADY_POSTED: "Ese archivo de apertura ya fue contabilizado.",
  OPENING_DOCUMENT_ALREADY_LOADED: "Un documento del archivo ya fue cargado en otra apertura.",
  OPENING_LOT_MOVED: "Algún lote de la apertura ya se movió; no se puede reversar.",
  STANDARD_COST_MISSING: "El producto no tiene costo estándar aprobado en esa área.",
  STANDARD_COST_CHANGED: "El costo estándar cambió desde que se preparó el archivo.",
  PRICE_LIST_MISSING: "No hay lista de precios vigente.",
  PRICE_MISSING: "El producto no tiene precio en la lista vigente.",
  SITE_ADDRESS_REQUIRED: "Indique la dirección de la obra para una entrega en obra.",
  QUANTITY_EXCEEDS_OPEN: "La cantidad supera lo pendiente de entregar del pedido.",
  OPEN_DELIVERIES: "El pedido tiene conduces abiertos.",
  TRANSPORT_REQUIRED: "Indique el vehículo y el chofer (o la placa y el chofer del cliente si retira en planta).",
  VEHICLE_OVER_CAPACITY: "La carga supera la capacidad del vehículo.",
  WEIGHING_INVALID: "La pesada no es válida: el bruto debe ser mayor que la tara.",
  LOCATION_INVALID: "La ubicación no es válida: debe ser una ubicación de existencias de la planta del documento.",
  INSUFFICIENT_STOCK: "No hay existencias suficientes en esa ubicación.",
  EVIDENCE_INVALID: "Indique la evidencia: referencia del archivo y su SHA-256 (64 caracteres hexadecimales).",
  POD_QUANTITIES_INVALID: "Lo recibido más lo devuelto no puede superar lo despachado.",
  EXCEPTION_REASON_REQUIRED: "Indique el motivo de la excepción (faltante o devolución).",
  // MFG-1: machines, shifts, recipes, runs, lots and cost collectors.
  NOT_RAW_MATERIAL: "Ese artículo no es una materia prima.",
  CODE_DUPLICATE: "Ya existe uno con ese código en la planta.",
  MACHINE_NOT_ACTIVE: "La máquina no está activa.",
  SHIFT_NOT_ACTIVE: "El turno no está activo.",
  RUN_EXISTS: "Ya hay una corrida para esa máquina, turno y fecha.",
  SUMMARY_EXISTS: "La corrida ya tiene un resumen de turno; no se puede cancelar.",
  MATERIALS_MISMATCH: "Registre el consumo real de cada material de la receta, una vez cada uno.",
  CURING_NOT_DONE: "El lote todavía no cumple su curado mínimo.",
  LOT_MOVED: "El lote ya se movió (liberado, bloqueado o desechado); el resumen no se puede revertir.",
  COLLECTOR_SETTLED: "El colector de costos ya está liquidado.",
  MONTH_NOT_ENDED: "El mes del colector todavía no ha terminado.",
  RUNS_OPEN: "El colector tiene corridas en proceso.",
  // FIS-1: fiscal authorizations (CONFOTUR).
  AUTHORIZATION_NOT_FOUND: "La autorización fiscal no existe.",
  AUTHORIZATION_INVALID_STATE: "La autorización fiscal no está en un estado que permita esta acción.",
  AUTHORIZATION_VERSION_CONFLICT: "La autorización cambió mientras la veía; recargue la página y vuelva a intentarlo.",
  AUTHORIZATION_EXPIRED: "El certificado está vencido (pasó su fecha de vigencia).",
  AUTHORIZATION_FIELD_INVALID:
    "Revise los datos: textos obligatorios, vigencia igual o posterior a la emisión, pedido del mismo cliente, cada producto y unidad una vez, cantidad (6 decimales) y neto (2 decimales) mayores que cero; un documento con tipo, referencia y SHA-256.",
  AUTHORIZATION_LINES_REQUIRED: "La autorización debe cubrir al menos un producto.",
  AUTHORIZATION_CERTIFICATE_REQUIRED: "Adjunte el certificado de exención de la DGII antes de enviar a verificación.",
  AUTHORIZATION_CERTIFICATE_DUPLICATE: "Ese número de certificado ya está registrado.",
  AUTHORIZATION_CUSTOMER_INVALID: "La autorización es de un cliente activo con RNC.",
  AUTHORIZATION_ITEM_INVALID: "El producto no es un producto terminado activo o la unidad no es la base ni tiene conversión vigente.",
  AUTHORIZATION_SAME_PERSON: "Quien registró la autorización no puede verificarla.",
  AUTHORIZATION_REASON_REQUIRED: "Indique el motivo (hasta 500 caracteres).",
  AUTHORIZATION_NOT_COVERED: "La autorización no cubre esas líneas (otro cliente, u otro producto o unidad); facture esas líneas aparte, con ITBIS.",
  AUTHORIZATION_EXCEEDED: "La cantidad o el neto superan lo disponible en la autorización para ese producto.",
  // QUO-1 (QUO1-04, E-QUO1-04-8): sales quotations.
  QUOTE_NOT_FOUND: "La cotización no existe.",
  QUOTE_INVALID_STATE: "La cotización no está en un estado que permita esta acción.",
  QUOTE_VERSION_CONFLICT: "La cotización cambió mientras la veía (o ya se convirtió en pedido); recargue la página y vuelva a intentarlo.",
  QUOTE_VALIDITY_INVALID: "La fecha de vigencia debe ser hoy o una fecha posterior.",
  QUOTE_NOTHING_TO_APPROVE: "Ninguna línea tiene un precio especial pendiente de aprobación; envíe la cotización.",
  QUOTE_PRICE_APPROVAL_REQUIRED: "Hay precios por debajo de la lista sin aprobar: envíe la cotización a aprobación primero.",
  QUOTE_SAME_PERSON: "Quien preparó la cotización no puede aprobar sus precios.",
  QUOTE_REASON_REQUIRED: "Indique el motivo (hasta 500 caracteres).",
  QUOTE_EXPIRED: "La cotización está vencida; cópiela con una nueva vigencia.",
  // FIS2-03 (E-FIS2-03-6): the 606 classification has no regression tests.
  FISCAL_RULE_TESTS_NOT_APPLICABLE: "La clasificación del 606 no lleva pruebas de regresión: queda lista para activar con su fuente oficial.",
};

export interface DescribedError {
  message: string;
  detail?: string;
  correlationId?: string;
}

export function describeError(error: unknown): DescribedError {
  if (error instanceof ApiError) {
    const known = ERROR_MESSAGES[error.code];
    return known
      ? { message: known, correlationId: error.correlationId }
      : { message: `Error ${error.code}`, detail: error.message, correlationId: error.correlationId };
  }
  return { message: "No se pudo comunicar con el servidor.", detail: error instanceof Error ? error.message : String(error) };
}
