// E-PR18b-11 / E-UX1-01-7: errors are shown by code, in Spanish. Every server code (the constants of the *Errors classes and
// SessionService) has a message: tests/Rochell.ArchitectureTests/ErrorCatalogueTests.cs checks it.
import { ApiError } from "@/api/client";

export const ERROR_MESSAGES: Readonly<Record<string, string>> = {
  SESSION_INVALID: "Su sesión no es válida. Inicie sesión de nuevo.",
  SESSION_EXPIRED: "Su sesión expiró. Inicie sesión de nuevo.",
  NOT_AUTHORIZED: "No tiene permiso para esta acción en esta empresa o planta.",
  STEP_UP_REQUIRED: "Esta acción requiere que vuelva a autenticarse.",
  CSRF_HEADER_REQUIRED: "Solicitud rechazada por seguridad. Recargue la página.",
  VERSION_CONFLICT: "El documento cambió mientras lo editaba. Recargue y vuelva a intentarlo.",
  CONCURRENCY_CONFLICT: "Hubo un conflicto con otra operación simultánea. Vuelva a intentarlo.",
  INVALID_REQUEST: "Los datos enviados no son válidos.",
  INVALID_PARAMETER: "Un filtro o parámetro no es válido.",
  NOT_FOUND: "El documento no existe o no pertenece a su planta.",
  SERVICE_UNAVAILABLE: "El servicio no está disponible en este ambiente.",
  INTERNAL_ERROR: "Error inesperado del sistema.",
  APPROVER_IS_CREATOR: "No puede aprobar un documento que usted creó.",
  APPROVAL_LIMIT_EXCEEDED: "El monto supera su límite de aprobación.",
  INVALID_STATE: "El documento no está en un estado que permita esta acción.",
  PLANT_MISMATCH: "El documento pertenece a otra planta.",
  SUPPLIER_NOT_ACTIVE: "El proveedor no está activo.",
  ITEM_NOT_ACTIVE: "El artículo no está activo.",
  UOM_NOT_CONVERTIBLE: "La unidad de medida no tiene conversión vigente para el artículo.",
  LINES_REQUIRED: "Agregue al menos una línea.",
  QUANTITY_INVALID: "La cantidad no es válida.",
  PRICE_INVALID: "El precio no es válido.",
  REASON_REQUIRED: "Indique el motivo.",
  RECEIPT_TOLERANCE_EXCEEDED: "La cantidad supera la tolerancia de recepción de la orden.",
  PURCHASE_ORDER_NOT_RECEIVABLE: "La orden no está aprobada para recibir.",
  LOCATION_NOT_IN_PLANT: "La ubicación no pertenece a la planta de la orden.",
  LOCATION_NOT_RECEIVABLE: "La materia prima no se recibe en CURADO ni en TRÁNSITO; elija la ubicación de recepción.",
  DUPLICATE_LINE: "Hay líneas repetidas.",
  WEIGH_TICKET_USED: "Ese ticket de báscula ya fue usado.",
  OCCURRED_IN_FUTURE: "La fecha y hora de la recepción no puede estar en el futuro.",
  GOODS_RECEIPT_NOT_REVERSIBLE: "La recepción no se puede reversar (sus lotes ya se movieron o está facturada).",
  ALREADY_INVOICED: "La cantidad ya fue facturada.",
  USE_RECEIPT_CORRECTION: "Use una corrección de recepción en lugar de una reversa.",
  QTY_EXCEPTION_NOT_APPROVABLE: "Un exceso de cantidad no se puede aprobar como excepción.",
  FISCAL_GATE_CLOSED: "No hay reglas fiscales activas para la fecha; no se puede contabilizar.",
  POSTING_PREREQUISITE_MISSING: "Falta configuración contable (regla de posteo, mapeo de cuentas o política) para contabilizar.",
  PERIOD_NOT_ENDED: "El período todavía no ha terminado.",
  COMPONENT_NOT_OPEN: "El componente no está abierto.",
  COMPONENT_NOT_CLOSED: "El componente no está cerrado.",
  INTEGRITY_NOT_SEALED: "Hay registros del período sin sellar; espere al sellador y vuelva a intentarlo.",
  RECONCILIATION_ERRORS: "Hay conciliaciones con errores que bloquean el cierre.",
  REOPEN_ALREADY_REQUESTED: "Ya hay una solicitud de reapertura pendiente.",
  REOPEN_NOT_REQUESTED: "No hay una solicitud de reapertura pendiente.",
  SAME_PERSON: "La misma persona no puede solicitar y aprobar.",
  FISCAL_NUMBER_INVALID: "El NCF no tiene un formato válido (B + 10 dígitos o E + 12 dígitos).",
  FISCAL_NUMBER_USED: "Ese NCF ya está registrado para el proveedor.",
  PRINTED_TOTAL_INVALID: "El total impreso debe ser mayor que cero y tener como máximo 2 decimales.",
  QTY_EXCEEDS_AVAILABLE: "La cantidad supera lo recibido y aún no facturado.",
  PO_LINE_NOT_INVOICEABLE: "La línea de la orden no se puede facturar.",
  AP_NOT_OPEN: "La cuenta por pagar ya tiene pagos o aplicaciones; no se puede reversar.",
  ALREADY_REVERSED: "El documento ya fue reversado.",
  EVIDENCE_REQUIRED: "Indique la evidencia (ticket corregido, foto o registro).",
  FOUR_EYES_REQUIRED: "Otra persona debe aprobar esta acción.",
  ACCOUNT_ROLE_INVALID: "Ese rol de cuenta o categoría no existe o no se puede mapear.",
  MAP_ACCOUNT_INVALID: "La cuenta no existe, está inactiva o no corresponde al rol: un rol de control va a una cuenta de control y un rol normal a una cuenta normal.",
  // FIN-1
  ACCOUNT_DUPLICATE: "Ya existe una cuenta con ese código.",
  ACCOUNT_INVALID: "La cuenta no es válida: revise código, nombre y clase.",
  ACCOUNT_HAS_BALANCE: "La cuenta tiene saldo; no se puede desactivar.",
  ACCOUNT_NOT_ALLOWED: "Los ajustes van solo a cuentas activas que no son de control; bancos, CxP e inventario se mueven por sus documentos.",
  LINES_INVALID: "Revise las líneas: cada una con débito o crédito mayor que cero (2 decimales) y al menos dos líneas.",
  JOURNAL_UNBALANCED: "Los débitos y los créditos deben ser iguales.",
  SUPPORT_INVALID: "El ajuste necesita su soporte: referencia y archivo.",
  STRUCTURE_INVALID: "La estructura no es válida: códigos únicos, una línea por cuenta y cuentas de las clases del reporte.",
  STRUCTURE_INCOMPLETE: "Hay cuentas activas sin línea en la estructura.",
  STRUCTURE_MISSING: "No hay una estructura de reporte aprobada.",
  ACCOUNT_CLASS_MISSING: "Hay cuentas activas sin clase.",
  DATE_INVALID: "La fecha no es válida.",
  LINE_NOT_FOUND: "La línea no existe en el documento.",
  RECEIPT_CORRECTION_NOT_PENDING: "La corrección ya no está pendiente.",
  RNC_INVALID: "El RNC no es válido.",
  RNC_DUPLICATE: "Ya existe un proveedor con ese RNC.",
  // FIS-1b: proformas.
  PROFORMA_MARK_INVALID: "Un pedido con exención en trámite indica si sus proformas se cobran con ITBIS o sin ITBIS.",
  PROFORMA_REQUIRED: "Ese conduce tiene proforma: se factura desde su proforma.",
  ALLOCATION_EXCEEDS_AVAILABLE: "El monto supera lo que queda disponible del recibo.",
  ALLOCATION_EXCEEDS_BALANCE: "El monto supera el saldo por cobrar de la proforma.",
  PROFORMA_NOT_OPEN: "La proforma ya no está abierta.",
  PROFORMA_OF_ANOTHER_CUSTOMER: "La proforma es de otro cliente.",
  ALLOCATION_NOT_FOUND: "El recibo no tiene esa asignación vigente.",
  PROFORMA_NOT_CERTIFIED: "Esa autorización cita proformas: solo cubre la factura de esas proformas.",
  PROFORMA_NOT_VOIDABLE: "Solo se anula una proforma abierta, sin cobros asignados y que ninguna autorización cite.",
  AUTHORIZATION_PROFORMA_INVALID: "Cada proforma debe estar abierta, ser del cliente y no estar en otra autorización.",
  REFUND_METHOD_INVALID: "La devolución se paga por transferencia o cheque.",
  REFUND_EXCEEDS_CREDIT_BALANCE: "El monto supera el saldo a favor disponible del recibo.",
  RECEIPT_NOT_REFUNDABLE: "Solo se devuelve dinero de un recibo vigente cuyo dinero ya está en el banco.",
  REFUND_NOT_MATCHABLE: "Solo una devolución liberada se empareja con el extracto.",
  MAIL_RECIPIENT_INVALID: "Revise los destinatarios: de 1 a 10 direcciones de correo válidas.",
  MAIL_FIELD_INVALID: "Revise el asunto (una línea, hasta 200 caracteres) y el mensaje (hasta 5,000 caracteres).",
  // IMP-01: bulk load of suppliers and customers.
  IMPORT_FILE_INVALID: "El archivo no se puede leer como la exportación de ADM Cloud (.xlsx o .csv con «Razón Social» e «ID Fiscal»).",
  IMPORT_FILE_TOO_LARGE: "El archivo supera 5 MB.",
  BATCH_INVALID: "Seleccione entre 1 y 500 registros.",
  // VS#2: treasury.
  BANK_ACCOUNT_INVALID: "El banco o el número de cuenta no son válidos (número: 5 a 30 dígitos).",
  BANK_ACCOUNT_DUPLICATE: "Esa cuenta bancaria ya está registrada.",
  BANK_ACCOUNT_NOT_ACTIVE: "La cuenta bancaria está cerrada.",
  BANK_ACCOUNT_ALIAS_INVALID: "El alias de la cuenta bancaria tiene como máximo 60 caracteres.",
  BANK_ACCOUNT_HAS_OPEN_ITEMS: "La cuenta tiene pagos pendientes o líneas del extracto sin conciliar.",
  GL_ACCOUNT_NOT_FOUND: "La cuenta contable no existe.",
  GL_ACCOUNT_NOT_ELIGIBLE: "La cuenta contable debe ser de control y no estar usada por otra cuenta bancaria ni por un mapa.",
  PARTY_BANK_ACCOUNT_NOT_VERIFIED: "La cuenta del proveedor no está verificada.",
  PARTY_BANK_ACCOUNT_NOT_PAYABLE: "La cuenta del proveedor todavía no se puede pagar (retención de 72 horas o reemplazada).",
  PAYMENT_NOT_PREPARED: "El pago ya no está preparado.",
  PAYMENT_NOT_REVERSIBLE: "Solo se revierte un pago liberado o compensado.",
  APPLICATIONS_REQUIRED: "Elija al menos una factura.",
  APPLICATION_DUPLICATE: "Una factura aparece dos veces en el pago.",
  APPLICATION_WRONG_SUPPLIER: "Todas las facturas deben ser del mismo proveedor.",
  APPLICATION_EXCEEDS_OPEN_AMOUNT: "El monto aplicado supera el saldo abierto de la factura.",
  AMOUNT_INVALID: "El monto no es válido (mayor que cero, máximo 2 decimales).",
  VALUE_DATE_BEFORE_INVOICE: "La fecha valor no puede ser anterior a la factura más reciente.",
  VALUE_DATE_IN_FUTURE: "Un pago se libera en su fecha valor o después.",
  BANK_FORMAT_MISSING: "No hay un formato de extracto para ese banco.",
  BANK_FILE_INVALID: "El archivo tiene filas que no se pueden leer; no se importó nada.",
  BANK_FILE_TOO_LARGE: "El archivo supera 5 MB.",
  STATEMENT_ALREADY_IMPORTED: "Ese archivo ya fue importado.",
  STATEMENT_FIELDS_REQUIRED: "El formato del banco no trae período o saldos: indíquelos.",
  STATEMENT_FIELDS_DISAGREE: "El período o los saldos indicados no coinciden con el archivo.",
  STATEMENT_BALANCE_MISMATCH: "Saldo inicial + créditos − débitos no da el saldo final.",
  LINE_OUTSIDE_PERIOD: "Hay líneas fuera del período del extracto; no se importó nada.",
  PERIOD_CLOSED: "El mes de esa fecha está cerrado (Bancos para un extracto, Ajustes contables para un ajuste); reábralo primero o use otra fecha.",
  LINE_NOT_UNMATCHED: "La línea ya no está sin conciliar.",
  LINE_NOT_MATCHED: "La línea no está conciliada.",
  LINE_NOT_DEBIT: "Esa acción es solo para líneas de débito.",
  PAYMENT_NOT_RELEASED: "Solo se concilia un débito con un pago liberado.",
  PAYMENT_NOT_REVERSED: "Una línea de crédito solo se concilia como devolución de un pago revertido.",
  PAYMENT_REVERSED: "La línea de un pago revertido queda conciliada.",
  RETURN_WITHOUT_TRANSFER: "El pago revertido nunca fue debitado por el banco: no hay devolución.",
  RETURN_ALREADY_MATCHED: "La devolución de ese pago ya está conciliada.",
  MATCH_WRONG_BANK_ACCOUNT: "La línea y el pago son de cuentas bancarias distintas.",
  MATCH_AMOUNT_DIFFERS: "El monto de la línea y el del pago no son iguales.",
  MATCH_DATE_OUTSIDE_WINDOW: "La fecha de la línea está fuera de la ventana permitida.",
  ROLE_UNKNOWN: "El rol no existe.",
  USER_INVALID: "El usuario no existe o no está activo.",
  SELF_REQUEST: "Nadie puede solicitar un rol para sí mismo.",
  ASSIGNMENT_NOT_FOUND: "El usuario ya no tiene ese rol.",
  ALREADY_ASSIGNED: "El usuario ya tiene ese rol.",
  REQUEST_NOT_FOUND: "La solicitud no existe.",
  REQUEST_NOT_PENDING: "La solicitud ya fue decidida.",
  SECOND_APPROVER_REQUIRED: "La decide una persona distinta de quien la pidió y del usuario afectado.",
  SOD_CONFLICT: "Ese rol choca con otro rol del usuario (segregación de funciones).",
  POLICY_MISSING: "Falta la política con los tramos de antigüedad: TREASURY para CxP, CREDIT para CxC (Contabilidad › Políticas).",
  // VS#3: customers, prices, fleet, opening stock, orders and deliveries.
  CUSTOMER_EXISTS: "Ya existe un cliente con ese RNC o cédula.",
  CUSTOMER_NOT_ACTIVE: "El cliente no está activo.",
  CUSTOMER_TERMS_REQUIRED: "El cliente necesita términos de crédito aprobados.",
  CREDIT_HOLD: "El cliente tiene el crédito retenido; el pedido irá a Crédito.",
  CREDIT_LIMIT_EXCEEDED: "El pedido supera el crédito disponible del cliente; irá a Crédito.",
  OVERDUE_DAYS_EXCEEDED: "El cliente tiene facturas vencidas por más días de los permitidos; el pedido irá a Crédito.",
  NOT_CUSTOMER: "Ese tercero no es cliente.",
  NOT_DRAFT: "Solo se puede cambiar mientras está en borrador.",
  FIELD_REQUIRED: "Complete los campos obligatorios.",
  FIELD_INVALID: "Un campo no tiene un formato válido.",
  NOT_FINISHED_GOOD: "El artículo no es un producto terminado.",
  IN_TRANSIT_EXISTS: "Hay unidades del producto en tránsito; apruebe el costo estándar cuando se entreguen o regresen.",
  RECIPE_NOT_ACTIVE: "La receta no está activa.",
  MATERIAL_PRICES_MISMATCH: "Debe dar un precio estándar para cada material de la receta, y solo para ellos.",
  PLATE_INVALID: "La placa no tiene un formato válido.",
  PLATE_DUPLICATE: "Ya existe un vehículo con esa placa.",
  NATIONAL_ID_INVALID: "La cédula debe tener 11 dígitos.",
  NATIONAL_ID_DUPLICATE: "Ya existe un chofer con esa cédula.",
  OPENING_FILE_INVALID: "El archivo de apertura tiene errores; revise el detalle.",
  OPENING_FILE_ALREADY_POSTED: "Ese archivo de apertura ya fue contabilizado.",
  OPENING_DOCUMENT_ALREADY_LOADED: "Un documento del archivo ya fue cargado en otra apertura.",
  OPENING_LOT_MOVED: "Algún lote de la apertura ya se movió; no se puede reversar.",
  STANDARD_COST_MISSING: "El producto no tiene costo estándar aprobado en esa área.",
  STANDARD_COST_CHANGED: "El costo estándar cambió desde que se preparó el archivo.",
  PRICE_LIST_MISSING: "No hay lista de precios vigente.",
  PRICE_MISSING: "El producto no tiene precio en la lista vigente.",
  SITE_ADDRESS_REQUIRED: "Indique la dirección de la obra para una entrega en obra.",
  QUANTITY_EXCEEDS_OPEN: "La cantidad supera lo pendiente de entregar del pedido.",
  OPEN_DELIVERIES: "El pedido tiene conduces abiertos.",
  TRANSPORT_REQUIRED: "Indique el vehículo y el chofer (o la placa y el chofer del cliente si retira en planta).",
  VEHICLE_OVER_CAPACITY: "La carga supera la capacidad del vehículo.",
  WEIGHING_INVALID: "La pesada no es válida: el bruto debe ser mayor que la tara.",
  LOCATION_INVALID: "La ubicación no es válida: debe ser una ubicación de existencias de la planta del documento.",
  INSUFFICIENT_STOCK: "No hay existencias suficientes en esa ubicación.",
  EVIDENCE_INVALID: "Indique la evidencia: referencia del archivo y su SHA-256 (64 caracteres hexadecimales).",
  POD_QUANTITIES_INVALID: "Lo recibido más lo devuelto no puede superar lo despachado.",
  EXCEPTION_REASON_REQUIRED: "Indique el motivo de la excepción (faltante o devolución).",
  // MFG-1: machines, shifts, recipes, runs, lots and cost collectors.
  NOT_RAW_MATERIAL: "Ese artículo no es una materia prima.",
  CODE_DUPLICATE: "Ya existe uno con ese código en la planta.",
  MACHINE_NOT_ACTIVE: "La máquina no está activa.",
  SHIFT_NOT_ACTIVE: "El turno no está activo.",
  RUN_EXISTS: "Ya hay una corrida para esa máquina, turno y fecha.",
  SUMMARY_EXISTS: "La corrida ya tiene un resumen de turno; no se puede cancelar.",
  MATERIALS_MISMATCH: "Registre el consumo real de cada material de la receta, una vez cada uno.",
  CURING_NOT_DONE: "El lote todavía no cumple su curado mínimo.",
  LOT_MOVED: "El lote ya se movió (liberado, bloqueado o desechado); el resumen no se puede revertir.",
  COLLECTOR_SETTLED: "El colector de costos ya está liquidado.",
  MONTH_NOT_ENDED: "El mes del colector todavía no ha terminado.",
  RUNS_OPEN: "El colector tiene corridas en proceso.",
  // FIS-1: fiscal authorizations (CONFOTUR).
  AUTHORIZATION_NOT_FOUND: "La autorización fiscal no existe.",
  AUTHORIZATION_INVALID_STATE: "La autorización fiscal no está en un estado que permita esta acción.",
  AUTHORIZATION_VERSION_CONFLICT: "La autorización cambió mientras la veía; recargue la página y vuelva a intentarlo.",
  AUTHORIZATION_EXPIRED: "El certificado está vencido (pasó su fecha de vigencia).",
  AUTHORIZATION_FIELD_INVALID:
    "Revise los datos: textos obligatorios, vigencia igual o posterior a la emisión, pedido del mismo cliente, cada producto y unidad una vez, cantidad (6 decimales) y neto (2 decimales) mayores que cero; un documento con tipo, referencia y SHA-256.",
  AUTHORIZATION_LINES_REQUIRED: "La autorización debe cubrir al menos un producto.",
  AUTHORIZATION_CERTIFICATE_REQUIRED: "Adjunte el certificado de exención de la DGII antes de enviar a verificación.",
  AUTHORIZATION_CERTIFICATE_DUPLICATE: "Ese número de certificado ya está registrado.",
  AUTHORIZATION_CUSTOMER_INVALID: "La autorización es de un cliente activo con RNC.",
  AUTHORIZATION_ITEM_INVALID: "El producto no es un producto terminado activo o la unidad no es la base ni tiene conversión vigente.",
  AUTHORIZATION_SAME_PERSON: "Quien registró la autorización no puede verificarla.",
  AUTHORIZATION_REASON_REQUIRED: "Indique el motivo (hasta 500 caracteres).",
  AUTHORIZATION_NOT_COVERED: "La autorización no cubre esas líneas (otro cliente, u otro producto o unidad); facture esas líneas aparte, con ITBIS.",
  AUTHORIZATION_EXCEEDED: "La cantidad o el neto superan lo disponible en la autorización para ese producto.",
  // QUO-1 (QUO1-04, E-QUO1-04-8): sales quotations.
  QUOTE_NOT_FOUND: "La cotización no existe.",
  QUOTE_INVALID_STATE: "La cotización no está en un estado que permita esta acción.",
  QUOTE_VERSION_CONFLICT: "La cotización cambió mientras la veía (o ya se convirtió en pedido); recargue la página y vuelva a intentarlo.",
  QUOTE_VALIDITY_INVALID: "La fecha de vigencia debe ser hoy o una fecha posterior.",
  QUOTE_NOTHING_TO_APPROVE: "Ninguna línea tiene un precio especial pendiente de aprobación; envíe la cotización.",
  QUOTE_PRICE_APPROVAL_REQUIRED: "Hay precios por debajo de la lista sin aprobar: envíe la cotización a aprobación primero.",
  QUOTE_SAME_PERSON: "Quien preparó la cotización no puede aprobar sus precios.",
  QUOTE_REASON_REQUIRED: "Indique el motivo (hasta 500 caracteres).",
  QUOTE_EXPIRED: "La cotización está vencida; cópiela con una nueva vigencia.",
  // FIS2-03 (E-FIS2-03-6): the 606 classification has no regression tests.
  FISCAL_RULE_TESTS_NOT_APPLICABLE: "La clasificación del 606 no lleva pruebas de regresión: queda lista para activar con su fuente oficial.",
  // UX1-01b (E-UX1-01-7): every remaining server code.
  // Identity and API
  LOGIN_REJECTED: "No se pudo iniciar sesión: use una cuenta de Google verificada del dominio de la empresa, vinculada a un usuario activo.",
  TEST_IDENTITY_UNAVAILABLE: "Esa identidad de prueba no existe, está desactivada o no tiene roles en esta empresa.",
  IDEMPOTENCY_KEY_REQUIRED: "Solicitud incompleta (falta la clave de idempotencia). Cierre el formulario, ábralo de nuevo y vuelva a intentarlo.",
  // Master data: items and units
  ITEM_CODE_INVALID: "El código del artículo debe tener de 2 a 40 caracteres: letras A–Z, dígitos, guion o guion bajo.",
  ITEM_CODE_DUPLICATE: "Ya existe un artículo con ese código en la empresa.",
  ITEM_CATEGORY_INVALID: "La categoría no es válida para ese tipo de artículo; elija una de la lista.",
  UOM_UNKNOWN: "La unidad de medida no existe.",
  CONVERSION_INVALID: "La conversión no es válida: el factor debe ser mayor que cero (hasta 8 decimales) y la unidad de origen distinta de la unidad base.",
  CONVERSION_RETROACTIVE: "La conversión debe empezar hoy o después, y después del inicio de la conversión vigente; el pasado no se recalcula.",
  // Inventory
  LOCATION_NOT_FOUND: "La ubicación no existe en esta empresa.",
  // Finance: configuration, policies, posting and close
  CONFIGURATION_NOT_FOUND: "La configuración (mapa de cuentas, versión de regla de posteo o de política) no existe.",
  CONFIGURATION_NOT_DRAFT: "Solo se puede cambiar o activar una configuración en borrador; cree una nueva versión.",
  EFFECTIVE_RANGE_OVERLAP: "La vigencia se cruza con una versión activa: la nueva debe empezar después de la fecha de inicio de la vigente.",
  RULE_DEFINITION_INVALID: "La definición de la regla de posteo no es válida: revise las líneas, los roles de cuenta y los auxiliares (solo las cuentas de control llevan auxiliar).",
  POLICY_UNKNOWN: "La política contable no existe.",
  POLICY_PARAMETERS_INVALID: "Los parámetros de la política no son válidos o falta la justificación; revise cada valor.",
  POSTING_UNBALANCED: "El asiento generado no cuadra (débitos distintos de créditos); revise la regla de posteo y el mapa de cuentas con Contabilidad.",
  JOURNAL_NOT_FOUND: "El asiento contable no existe.",
  PERIOD_NOT_FOUND: "El período contable no existe o no tiene ese componente de cierre.",
  UNKNOWN_COMPONENT: "El componente de cierre no existe.",
  UNKNOWN_RECONCILIATION: "La conciliación indicada no existe.",
  // Tax: fiscal rules and sources
  FISCAL_RULE_INVALID: "La definición de la regla fiscal no es válida: revise el código, la tasa, el efecto, la base y los tipos de contribuyente.",
  FISCAL_RULE_KIND_MISMATCH: "Ya existe una regla con ese código de otro tipo; use otro código o el tipo correcto.",
  FISCAL_RULE_VERSION_NOT_FOUND: "La versión de la regla fiscal no existe.",
  FISCAL_RULE_VERSION_NOT_CONFIGURABLE: "La versión ya está activa o retirada; configure una nueva versión.",
  FISCAL_RULE_VERSION_NOT_READY: "La versión no está lista para activar: necesita una fuente oficial vigente y una corrida de pruebas aprobada.",
  ACTIVATOR_IS_CONFIGURER: "Quien configuró la versión de la regla fiscal no puede activarla; otra persona debe hacerlo.",
  ANOTHER_ITBIS_RULE_ACTIVE: "Ya hay otra regla activa de ese tipo (ITBIS o clasificación del 606) para esa fecha; retírela antes de activar esta.",
  FISCAL_PRODUCTION_SOURCE_REQUIRED: "En producción la versión solo se activa con al menos una fuente oficial de producción vinculada.",
  FISCAL_SOURCE_INVALID: "La fuente no es válida: complete los textos, el SHA-256 del documento (64 caracteres), el ambiente, una consulta que no esté en el futuro y una vigencia final posterior a la inicial.",
  FISCAL_SOURCE_NOT_FOUND: "La fuente fiscal no existe.",
  FISCAL_SOURCE_NOT_EFFECTIVE: "La fuente no está vigente en la fecha de inicio de la versión; use una fuente vigente para esa fecha.",
  TEST_CASES_REQUIRED: "Agregue al menos un caso de prueba.",
  TAX_SUBJECT_INVALID: "No se pudo calcular el impuesto: falta el tercero, las líneas, o un artículo o proveedor no existe.",
  // Procurement
  PURCHASE_ORDER_NOT_FOUND: "La orden de compra no existe.",
  ALREADY_RECEIVED: "La orden ya tiene recepciones; no se puede cancelar.",
  GOODS_RECEIPT_NOT_FOUND: "La recepción o su línea no existe.",
  RECEIPT_CORRECTION_NOT_FOUND: "La corrección de recepción no existe.",
  VALUE_TOO_SMALL: "La cantidad es tan pequeña que no se puede valorar; revise la cantidad o la unidad.",
  SUPPLIER_INVOICE_NOT_FOUND: "La factura del proveedor no existe.",
  LINE_KIND_NOT_SUPPORTED: "Ese tipo de línea no se puede facturar: cada línea debe facturar una línea de inventario de una orden de compra.",
  NOTHING_TO_REPOST: "El evento no tiene un asiento contabilizado de esa regla para recontabilizar.",
  REPOST_RULE_INCOMPATIBLE: "La versión vigente de la regla de posteo no tiene todas las líneas del asiento original; no se puede recontabilizar tal cual.",
  NOT_AN_ORPHAN_RESIDUAL: "No hay un valor residual huérfano: la posición todavía tiene cantidad o su valor ya es cero.",
  // Treasury: supplier bank accounts and statement matching
  PARTY_BANK_ACCOUNT_REVIEW_PENDING: "El proveedor ya tiene una cuenta bancaria en revisión; verifíquela o recházela primero.",
  PARTY_BANK_ACCOUNT_NOT_IN_REVIEW: "Solo se verifica o rechaza una cuenta en revisión.",
  VERIFICATION_EVIDENCE_REQUIRED: "Describa la verificación (al menos 20 caracteres): a quién llamó, a qué número y cuándo.",
  MATCH_TARGET_REQUIRED: "Elija un recibo o un depósito para conciliar la línea, no ambos.",
  RECEIPT_NOT_MATCHABLE: "El recibo o depósito no se puede conciliar con esa línea: un crédito va con una transferencia registrada o un depósito pendiente, y un débito solo con un cheque devuelto.",
  // Sales: invoices
  DELIVERY_LINE_NOT_BILLABLE: "Cada línea debe ser de un conduce entregado de este cliente y con cantidad pendiente de facturar.",
  INVOICE_EXCEEDS_DELIVERED: "La cantidad supera lo entregado y aún no facturado del conduce.",
  ECF_TYPE_INVALID: "El tipo de e-CF debe ser 31 (crédito fiscal) o 32 (consumo); una factura con autorización de exención es e-CF 44.",
  ENCF_INVALID: "El e-NCF no tiene el formato correcto: E + tipo de e-CF + 10 dígitos (E34 para notas de crédito).",
  ENCF_DUPLICATE: "Ese e-NCF ya está registrado.",
  FISCAL_DOCUMENT_MISMATCH: "El e-CF no coincide con el documento (ITBIS o total), falta el código de seguridad o la fecha de emisión está en el futuro; revise los datos del e-CF.",
  INVOICE_NOT_VOIDABLE: "Solo se anula una factura emitida, sin e-CF aceptado y sin cobros aplicados; si ya está fiscalizada, haga una nota de crédito.",
  // Sales: credit notes
  INVOICE_NOT_CREDITABLE: "La nota de crédito requiere una factura fiscalizada (e-CF aceptado) y no anulada.",
  CREDIT_NOTE_REASON_INVALID: "Elija el motivo (descuento, error de precio u otro) y escriba la explicación.",
  CREDIT_EXCEEDS_INVOICE_LINE: "El monto supera lo que la línea de la factura aún puede acreditar; si otra nota tomó parte, prepare esta de nuevo.",
  CREDIT_EXCEEDS_OPEN_RECEIVABLE: "La nota supera el saldo pendiente de la factura; los saldos a favor y devoluciones de dinero no están disponibles.",
  // Sales: receipts, deposits and withholdings
  RECEIPT_METHOD_INVALID: "La forma de cobro debe ser transferencia, cheque o efectivo.",
  RECEIPT_DATE_INVALID: "La fecha no es válida: no puede ser futura (no se aceptan cheques posfechados) y una retención va entre la fecha de la factura y hoy.",
  APPLICATION_EXCEEDS_UNAPPLIED: "El total aplicado supera el monto del recibo que queda sin aplicar.",
  APPLICATION_EXCEEDS_OPEN: "El monto aplicado supera el saldo pendiente de la factura.",
  APPLICATION_NOT_FOUND: "Esa aplicación ya no existe o ya fue deshecha; recargue la página.",
  INVOICE_OF_ANOTHER_CUSTOMER: "La factura es de otro cliente; solo aplique facturas del cliente del recibo.",
  INVOICE_NOT_OPEN: "La factura no está pendiente de cobro (debe estar confirmada o parcialmente pagada).",
  RECEIPT_NOT_DEPOSITABLE: "Solo se depositan recibos en cheque o efectivo que estén en tránsito.",
  RECEIPT_NOT_BOUNCEABLE: "Solo se marca como devuelto un cheque ya depositado.",
  RECEIPT_NOT_REVERSIBLE: "Solo se reversa un recibo sin aplicaciones, que no esté depositado ni conciliado con el banco; deshaga eso primero.",
  WITHHOLDING_KIND_INVALID: "La retención debe ser de ITBIS o de ISR.",
  WITHHOLDING_EXCEEDS: "La retención supera el saldo pendiente de la factura o, si es de ITBIS, el ITBIS de la factura.",
  WITHHOLDING_CERTIFICATE_DUPLICATE: "Ese número de certificado de retención ya está registrado para este cliente.",
};

export interface DescribedError {
  message: string;
  /** Technical detail (the server's English message), shown folded under "Detalle técnico". */
  detail?: string;
  correlationId?: string;
}

/** E-UX1-01-7: a known code reads its Spanish message; an unknown one "No se pudo completar (CODE)." with the server's detail. */
export function describeError(error: unknown): DescribedError {
  if (error instanceof ApiError) {
    const known = ERROR_MESSAGES[error.code];
    return known
      ? { message: known, correlationId: error.correlationId }
      : { message: `No se pudo completar (${error.code}).`, detail: error.message, correlationId: error.correlationId };
  }
  return { message: "No se pudo comunicar con el servidor.", detail: error instanceof Error ? error.message : String(error) };
}
