// E-PR18b-11: errors are shown by code, in Spanish. Unknown codes fall back to the API message and the correlation id.
import { ApiError } from "@/api/client";

export const ERROR_MESSAGES: Readonly<Record<string, string>> = {
  SESSION_INVALID: "Su sesión no es válida. Inicie sesión de nuevo.",
  SESSION_EXPIRED: "Su sesión expiró. Inicie sesión de nuevo.",
  NOT_AUTHORIZED: "No tiene permiso para esta acción en esta empresa o planta.",
  STEP_UP_REQUIRED: "Esta acción requiere que vuelva a autenticarse.",
  CSRF_HEADER_REQUIRED: "Solicitud rechazada por seguridad. Recargue la página.",
  VERSION_CONFLICT: "El documento cambió mientras lo editaba. Recargue y vuelva a intentarlo.",
  CONCURRENCY_CONFLICT: "Hubo un conflicto con otra operación simultánea. Vuelva a intentarlo.",
  INVALID_REQUEST: "Los datos enviados no son válidos.",
  INVALID_PARAMETER: "Un filtro o parámetro no es válido.",
  NOT_FOUND: "El documento no existe o no pertenece a su planta.",
  SERVICE_UNAVAILABLE: "El servicio no está disponible en este ambiente.",
  INTERNAL_ERROR: "Error inesperado del sistema.",
  APPROVER_IS_CREATOR: "No puede aprobar un documento que usted creó.",
  APPROVAL_LIMIT_EXCEEDED: "El monto supera su límite de aprobación.",
  INVALID_STATE: "El documento no está en un estado que permita esta acción.",
  PLANT_MISMATCH: "El documento pertenece a otra planta.",
  SUPPLIER_NOT_ACTIVE: "El proveedor no está activo.",
  ITEM_NOT_ACTIVE: "El artículo no está activo.",
  UOM_NOT_CONVERTIBLE: "La unidad de medida no tiene conversión vigente para el artículo.",
  LINES_REQUIRED: "Agregue al menos una línea.",
  QUANTITY_INVALID: "La cantidad no es válida.",
  PRICE_INVALID: "El precio no es válido.",
  REASON_REQUIRED: "Indique el motivo.",
  RECEIPT_TOLERANCE_EXCEEDED: "La cantidad supera la tolerancia de recepción de la orden.",
  PURCHASE_ORDER_NOT_RECEIVABLE: "La orden no está aprobada para recibir.",
  LOCATION_NOT_IN_PLANT: "La ubicación no pertenece a la planta de la orden.",
  DUPLICATE_LINE: "Hay líneas repetidas.",
  WEIGH_TICKET_USED: "Ese ticket de báscula ya fue usado.",
  OCCURRED_IN_FUTURE: "La fecha y hora de la recepción no puede estar en el futuro.",
  GOODS_RECEIPT_NOT_REVERSIBLE: "La recepción no se puede reversar (sus lotes ya se movieron o está facturada).",
  ALREADY_INVOICED: "La cantidad ya fue facturada.",
  USE_RECEIPT_CORRECTION: "Use una corrección de recepción en lugar de una reversa.",
  QTY_EXCEPTION_NOT_APPROVABLE: "Un exceso de cantidad no se puede aprobar como excepción.",
  FISCAL_GATE_CLOSED: "No hay reglas fiscales activas para la fecha; no se puede contabilizar.",
  POSTING_PREREQUISITE_MISSING: "Falta configuración contable (regla de posteo, mapeo de cuentas o política) para contabilizar.",
  PERIOD_NOT_ENDED: "El período todavía no ha terminado.",
  COMPONENT_NOT_OPEN: "El componente no está abierto.",
  COMPONENT_NOT_CLOSED: "El componente no está cerrado.",
  INTEGRITY_NOT_SEALED: "Hay registros del período sin sellar; espere al sellador y vuelva a intentarlo.",
  RECONCILIATION_ERRORS: "Hay conciliaciones con errores que bloquean el cierre.",
  REOPEN_ALREADY_REQUESTED: "Ya hay una solicitud de reapertura pendiente.",
  REOPEN_NOT_REQUESTED: "No hay una solicitud de reapertura pendiente.",
  SAME_PERSON: "La misma persona no puede solicitar y aprobar.",
  FISCAL_NUMBER_INVALID: "El NCF no tiene un formato válido (B + 10 dígitos o E + 12 dígitos).",
  FISCAL_NUMBER_USED: "Ese NCF ya está registrado para el proveedor.",
  QTY_EXCEEDS_AVAILABLE: "La cantidad supera lo recibido y aún no facturado.",
  PO_LINE_NOT_INVOICEABLE: "La línea de la orden no se puede facturar.",
  AP_NOT_OPEN: "La cuenta por pagar ya tiene pagos o aplicaciones; no se puede reversar.",
  ALREADY_REVERSED: "El documento ya fue reversado.",
  EVIDENCE_REQUIRED: "Indique la evidencia (ticket corregido, foto o registro).",
  FOUR_EYES_REQUIRED: "Otra persona debe aprobar esta acción.",
  // FIN-1
  ACCOUNT_DUPLICATE: "Ya existe una cuenta con ese código.",
  ACCOUNT_INVALID: "La cuenta no es válida: revise código, nombre y clase.",
  ACCOUNT_HAS_BALANCE: "La cuenta tiene saldo; no se puede desactivar.",
  ACCOUNT_NOT_ALLOWED: "Los ajustes van solo a cuentas activas que no son de control; bancos, CxP e inventario se mueven por sus documentos.",
  LINES_INVALID: "Revise las líneas: cada una con débito o crédito mayor que cero (2 decimales) y al menos dos líneas.",
  JOURNAL_UNBALANCED: "Los débitos y los créditos deben ser iguales.",
  SUPPORT_INVALID: "El ajuste necesita su soporte: referencia y archivo.",
  STRUCTURE_INVALID: "La estructura no es válida: códigos únicos, una línea por cuenta y cuentas de las clases del reporte.",
  STRUCTURE_INCOMPLETE: "Hay cuentas activas sin línea en la estructura.",
  STRUCTURE_MISSING: "No hay una estructura de reporte aprobada.",
  ACCOUNT_CLASS_MISSING: "Hay cuentas activas sin clase.",
  DATE_INVALID: "La fecha no es válida.",
  LINE_NOT_FOUND: "La línea no existe en el documento.",
  RECEIPT_CORRECTION_NOT_PENDING: "La corrección ya no está pendiente.",
  RNC_INVALID: "El RNC no es válido.",
  RNC_DUPLICATE: "Ya existe un proveedor con ese RNC.",
  // VS#2: treasury.
  BANK_ACCOUNT_INVALID: "El banco o el número de cuenta no son válidos (número: 5 a 30 dígitos).",
  BANK_ACCOUNT_DUPLICATE: "Esa cuenta bancaria ya está registrada.",
  BANK_ACCOUNT_NOT_ACTIVE: "La cuenta bancaria está cerrada.",
  BANK_ACCOUNT_HAS_OPEN_ITEMS: "La cuenta tiene pagos pendientes o líneas del extracto sin conciliar.",
  GL_ACCOUNT_NOT_FOUND: "La cuenta contable no existe.",
  GL_ACCOUNT_NOT_ELIGIBLE: "La cuenta contable debe ser de control y no estar usada por otra cuenta bancaria ni por un mapa.",
  PARTY_BANK_ACCOUNT_NOT_VERIFIED: "La cuenta del proveedor no está verificada.",
  PARTY_BANK_ACCOUNT_NOT_PAYABLE: "La cuenta del proveedor todavía no se puede pagar (retención de 72 horas o reemplazada).",
  PAYMENT_NOT_PREPARED: "El pago ya no está preparado.",
  PAYMENT_NOT_REVERSIBLE: "Solo se revierte un pago liberado o compensado.",
  APPLICATIONS_REQUIRED: "Elija al menos una factura.",
  APPLICATION_DUPLICATE: "Una factura aparece dos veces en el pago.",
  APPLICATION_WRONG_SUPPLIER: "Todas las facturas deben ser del mismo proveedor.",
  APPLICATION_EXCEEDS_OPEN_AMOUNT: "El monto aplicado supera el saldo abierto de la factura.",
  AMOUNT_INVALID: "El monto no es válido (mayor que cero, máximo 2 decimales).",
  VALUE_DATE_BEFORE_INVOICE: "La fecha valor no puede ser anterior a la factura más reciente.",
  VALUE_DATE_IN_FUTURE: "Un pago se libera en su fecha valor o después.",
  BANK_FORMAT_MISSING: "No hay un formato de extracto para ese banco.",
  BANK_FILE_INVALID: "El archivo tiene filas que no se pueden leer; no se importó nada.",
  BANK_FILE_TOO_LARGE: "El archivo supera 5 MB.",
  STATEMENT_ALREADY_IMPORTED: "Ese archivo ya fue importado.",
  STATEMENT_FIELDS_REQUIRED: "El formato del banco no trae período o saldos: indíquelos.",
  STATEMENT_FIELDS_DISAGREE: "El período o los saldos indicados no coinciden con el archivo.",
  STATEMENT_BALANCE_MISMATCH: "Saldo inicial + créditos − débitos no da el saldo final.",
  LINE_OUTSIDE_PERIOD: "Hay líneas fuera del período del extracto; no se importó nada.",
  PERIOD_CLOSED: "El mes de esa fecha está cerrado (Bancos para un extracto, Ajustes contables para un ajuste); reábralo primero o use otra fecha.",
  LINE_NOT_UNMATCHED: "La línea ya no está sin conciliar.",
  LINE_NOT_MATCHED: "La línea no está conciliada.",
  LINE_NOT_DEBIT: "Esa acción es solo para líneas de débito.",
  PAYMENT_NOT_RELEASED: "Solo se concilia un débito con un pago liberado.",
  PAYMENT_NOT_REVERSED: "Una línea de crédito solo se concilia como devolución de un pago revertido.",
  PAYMENT_REVERSED: "La línea de un pago revertido queda conciliada.",
  RETURN_WITHOUT_TRANSFER: "El pago revertido nunca fue debitado por el banco: no hay devolución.",
  RETURN_ALREADY_MATCHED: "La devolución de ese pago ya está conciliada.",
  MATCH_WRONG_BANK_ACCOUNT: "La línea y el pago son de cuentas bancarias distintas.",
  MATCH_AMOUNT_DIFFERS: "El monto de la línea y el del pago no son iguales.",
  MATCH_DATE_OUTSIDE_WINDOW: "La fecha de la línea está fuera de la ventana permitida.",
  ROLE_UNKNOWN: "El rol no existe.",
  USER_INVALID: "El usuario no existe o no está activo.",
  SELF_REQUEST: "Nadie puede solicitar un rol para sí mismo.",
  ASSIGNMENT_NOT_FOUND: "El usuario ya no tiene ese rol.",
  ALREADY_ASSIGNED: "El usuario ya tiene ese rol.",
  REQUEST_NOT_FOUND: "La solicitud no existe.",
  REQUEST_NOT_PENDING: "La solicitud ya fue decidida.",
  SECOND_APPROVER_REQUIRED: "La decide una persona distinta de quien la pidió y del usuario afectado.",
  SOD_CONFLICT: "Ese rol choca con otro rol del usuario (segregación de funciones).",
  POLICY_MISSING: "Falta la política TREASURY con los tramos de antigüedad (Contabilidad › Políticas).",
};

export interface DescribedError {
  message: string;
  detail?: string;
  correlationId?: string;
}

export function describeError(error: unknown): DescribedError {
  if (error instanceof ApiError) {
    const known = ERROR_MESSAGES[error.code];
    return known
      ? { message: known, correlationId: error.correlationId }
      : { message: `Error ${error.code}`, detail: error.message, correlationId: error.correlationId };
  }
  return { message: "No se pudo comunicar con el servidor.", detail: error instanceof Error ? error.message : String(error) };
}
