namespace Rochell.Platform.Commands;

/// <summary>Every command carries the tenant, the acting session and a client-generated idempotency key (ADR-021).</summary>
public interface ICommand
{
    Guid CompanyId { get; }

    Guid SessionId { get; }

    /// <summary>Generated by the client when the intent is created (e.g. when the form opens), not per click.</summary>
    string IdempotencyKey { get; }
}

/// <summary>Business logic of one command. Runs inside the command transaction; must not perform external I/O.</summary>
public interface ICommandHandler<in TCommand>
    where TCommand : ICommand
{
    /// <summary>Stable name stored in core.command_log.command_type.</summary>
    string CommandType { get; }

    /// <summary>Returns the JSON result payload stored in command_log and returned to duplicates.</summary>
    Task<string> HandleAsync(TCommand command, CommandContext context, CancellationToken cancellationToken);
}

/// <summary>Business rule rejection. Nothing is committed; request_log records REJECTED_DOMAIN.</summary>
public sealed class DomainException : Exception
{
    public DomainException()
    {
    }

    public DomainException(string message)
        : base(message)
    {
        Code = "DOMAIN_RULE";
    }

    public DomainException(string code, string message)
        : base(message)
    {
        Code = code;
    }

    public DomainException(string message, Exception innerException)
        : base(message, innerException)
    {
        Code = "DOMAIN_RULE";
    }

    public string Code { get; } = "DOMAIN_RULE";
}

/// <summary>Result of a command. <see cref="Duplicate"/> is true when an identical earlier command's result was returned.</summary>
public sealed record CommandResult(Guid CommandId, Guid ResultRef, string ResultPayload, bool Duplicate);

/// <summary>An event to append inside the command transaction.</summary>
public sealed record EventDraft(
    string EventType,
    int SchemaVersion,
    string AggregateType,
    Guid AggregateId,
    long AggregateVersion,
    string PayloadJson,
    bool Publish,
    DateTime? OccurredAt = null,
    DateOnly? BusinessDate = null,
    Guid? CausationId = null);
