namespace Rochell.Platform.Ids;

/// <summary>ADR-029: technical keys are UUIDv7 generated by the application before any INSERT.</summary>
public interface IIdGenerator
{
    Guid NewId();
}

public sealed class UuidV7Generator : IIdGenerator
{
    public static UuidV7Generator Instance { get; } = new();

    public Guid NewId() => Guid.CreateVersion7();
}
